// Auto-generated by scripts/generate-env.js
export const environment = {
  production: true,
  apiUrl: 'https://example.ngrok.io ',
  serverBasePath: 'https://example.ngrok.io ',
  mockAuth: false
};
