// scripts/generate-env.js
// Genera src/environments/environment.prod.ts usando la variable de entorno BACKEND_URL
const fs = require('fs');
const path = require('path');

const backendRaw = process.env.BACKEND_URL || process.env.NETLIFY_BACKEND_URL || 'https://patita-solidaria-backend.onrender.com';
const backend = (typeof backendRaw === 'string' ? backendRaw.trim() : backendRaw);

const content = `// Auto-generated by scripts/generate-env.js
export const environment = {
  production: true,
  apiUrl: '${backend}',
  serverBasePath: '${backend}',
  mockAuth: false
};
`;

const outPath = path.join(__dirname, '..', 'src', 'environments', 'environment.prod.ts');
fs.writeFileSync(outPath, content, { encoding: 'utf8' });
console.log('Wrote', outPath, 'with BACKEND_URL=' + backend);
